# -*- coding: utf-8 -*-
"""stock project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-F_uszL-LRuLgrZxyYJtANxJTi4oqeoI
"""

import pandas as pd
import numpy as np
import math as m

dates = pd.date_range(start='2025-01-01',periods=365)
np.random.seed(42)
initial_price = 100
volatility = 0.015
drift = 0.0006
price_history = [initial_price]

for date in range(1,len(dates)):
  random_shock = np.random.normal(loc=0,scale=volatility)
  tot_daily_change = drift + random_shock
  pre_data = price_history[-1]
  today_price = price_history[-1] * (1 + tot_daily_change)
  price_history.append(today_price)
df = pd.DataFrame(
    {
        'Date' : dates,
        'Closed_price' : price_history
    }
)
df['Daily_Return'] = df['Closed_price'].pct_change()
df['Ma_20'] = df['Closed_price'].rolling(window=20).mean()
df['daily_volatility'] = df['Daily_Return'].rolling(window=14).std()
print(df.tail())
df.to_excel("Stock_data.xlsx",index=False)
print("Data generated and exported!")

from google.colab import files
file = files.upload()

from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

file = pd.read_excel('/content/Stock_data.xlsx')
print(file.head())

#performing arima(0,1,0) - since the random shocks are completely new for everyday, it does'nt exhibit correlation and so the same for moving avg
clean_return = df['Daily_Return'].dropna()
adf_result = adfuller(clean_return)

print(f"ADF Statistic")
print(f"ADF Statistic: {adf_result[0]}")
print(f"p-value: {adf_result[1]:.4f}")
print(f"Critical values: ")
for key, value in adf_result[4].items():
  print(f"{key} : {value:.4f}")

if adf_result[1] <= 0.05:
  print("The data is stationary, proceed with 1st order differencing")
else:
  print("The data is non-stationary, differentiate again for further analysis")
#model
model = ARIMA(df['Closed_price'],order=(0,1,0))
model_result = model.fit()
print(model_result.summary())

predicted_direction = np.where(df['Closed_price'] > df['Ma_20'],1,0)
true_dir = np.where(df['Daily_Return'] > 0,1,0)
ConfusionMatrixDisplay.from_predictions(true_dir,predicted_direction,display_labels=['Down','Up'],cmap='Blues')
plt.show()